#!/usr/bin/env python3

try:
	import rrasm;
except:
	import sys;
	sys.path.append("/usr/local/share/rrasm/");
	import rrasm;

import argparse;

parser = argparse.ArgumentParser(prog="rrasm", description="Roadrunner Assembler");
rrasm.init_parser(parser);

args = parser.parse_args();
rrasm.main(args);