#!/usr/bin/env python3

try:
	import rrdis;
except:
	import sys;
	sys.path.append("/usr/local/share/rrdis/");
	import rrdis;

import argparse;

parser = argparse.ArgumentParser(prog="rrdis", description="Roadrunner Dissembler");
rrdis.init_parser(parser);

args = parser.parse_args();
rrdis.main(args);